<a href="https://colab.research.google.com/github/wavallejol/ColabChem/blob/main/Sesi%C3%B3n1_Intro_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Sesión 1: Introducción a Google Colaboratory**
***William Vallejo***
# **Objetivos**
 
1.   Conocer el entorno Google Colaboratory
2.   Aprender comandos basicos de programación

#**Introducción**
---
 
Este documento es una guía introductoria para aplicar conceptos básicos de programación con <a href="https://es.wikipedia.org/wiki/Python">phyton</a> a la resolución de ejercicios de química ⚗🧪. Phyton es un lenguaje de programación utilizado en una gran variedad de aplicaciones, con la ventaja de aplicabilidad a diferentes plataformas de trabajo, además, phyton es un software de acceso abierto (open source), siendo accesible a cualquier persona que desee utilizarlo 😆 .  Para dearrollar esta guía introductoria, no se requerie ningún concepto previo de programación. Los diferentes links te conectaran con páginas de internet para revisar los conceptos desconocidos o que debas recordar 📖..
 
 <a href="https://colab.research.google.com/notebooks/intro.ipynb?hl=es-419">Google Colaboratory</a> (también conocido como Google Colabs) es una maquina virtual en la nube que permite ejecutar programación de phyton sin configurar nada en tu computador (descargar o instalar programas nuevos); lo único que necesitas es acceso a internet y una cuenta de gmail, incluso puedes trabajar directamente en tu celular 📱.  Además, te da la facilidad de compartir el contenido de una manera sencilla y eficaz a través del Drive 🗂. Puedes ver este <a href="https://www.youtube.com/watch?v=inN8seMm7UI">video introductorio</a> sobre google Colabs (duración 3:09 minutos). Una de las ventajas de utilizar códigos de programación para tratamiento de datos experimentales y/o teóricos es que puedes crear  <a href="https://es.m.wikipedia.org/wiki/Subrutina">rutinas</a> de trabajo (pequeños códigos) para resolver icongnitas, extraer y/o visualizar informacion. Estas rutinas pueden ser utilizadas todas la veces que quieras y pueden ser adaptadas según tus necesidades. Normalmente, la rutina esta compuesta de 3 elementos ✔: 
 
(i) La entrada: Puede ser un número, una función, una matriz.
 
(ii) El proceso: Representa aquello que haremos con nuestra entrada (por ejemplo: una operación matemática, lógica, comparativa).
 
(iii) La salida: Representa el resultado obtenido de aplicar el proceso sobre nuestra entrada (por ejemplo: el resultado de una operación, una gráfica... etc). 

Normalmente, deberíamos crear un archivo donde escribimos nuestra rutina (definimos entradas, proceso y salida), luego deberíamos guardar nuestro archivo y finalmente deberíamos utilizar el software de phyton para ejecutar la rutina. En Google Colabs nos ahorramos los dos primeros pasos. Por medio de la maquina virtual en la nube sólo debemos escribir la rutina y luego la podemos ejecutar sin ningún paso adicional. En Google Colabs tenemos dos tipos de celda a través de las cuales podremos trabajar: 
 
(¡) La celda de texto 🔤: permite adicionar texto, links y figuras para brindar información (esto que lees esta escrito en una celda de texto). 
 
(ii) El segundo tipo de celda que tenemos es la celda de código ⌨ donde se alimenta  la entrada, el programa y la salida de nuestra rutina. la celda que encuentras a continuación es un ejemplo de una celda de codigo:

In [ ]:
# aqui vamos a escribir nuestro codigo

En la celda de código, el texto que coloques despues del simbolo `#` se entenderá como información de aclaración y no hace parte de la rutina que se ejecurará.
 
En este punto podemos dar nuestros primeros pasos para conocer un poco de esta poderosa herramienta.

#**Mis primeros programas**
---
Iniciaremos con nuestro primer programa: utilizaremos el comando `print()`, este comando genera como salida lo que se coloque entre comillas dentro del paréntesis. En la siguiente celda de código colocaremos nuestro primer programa.
 
Presiona clic en la siguiente celda de código y luego da clic en el ícono de "play" ▶️  que aparece en el costado izquierdo de la celda de código.

In [ ]:
 print("hola mundo") # después de dar play al icono en la siguiente celda aparecera como salida lo que hayas escrito

Como puedes observar luego de que se ha ejecutado la instrucción se generó  como "salida" el mensaje que se había escrito dentro del comando `print()`.  Ahora, en la siguiente celda escribe el código para que se genere como salida tu nombre.

Ahora ya haz escrito tu primera rutina, un primer paso en el aprendizaje de esta poderosa herramienta. Ahora probaremos el comado `input()`, este comando nos permite leer información introducida por un usuario desde el teclado. Oprime el icono de play ▶️ de la siguiente celda de código para ver un ejemplo, la rutina te saludará y preguntará tu nombre. Escríbelo y luego oprime la tecla enter.

In [ ]:
print("Hola, sere tu guia en esta primera sesión, ¿como te llamas?")
Nombre=input()
print("Es maravilloso que te interese aprender phyton,", Nombre)

La rutina anterior te permitió leer la infomación introducida por el usuario (en este caso tú) en respuesta a una pregunta previamente establecida mediante el código.

 
Python reconoce diferente tipo de información que podemos generar y utilizar durante nuestros experimentos. La tabla 1 muestra un resumen del tipo de información que se puede manejar.
 
<div align = "center"> Tabla 1. Descripción de diferente tipo de informacion que reconoce phyton. (Tomado de: A.Moreno, S. Corcoles, 2018.</a>)</div>
 
Tipo de información| Descripción
-------------------|------------------
 Entero | Número son decimales, positivo y negativo, también se incluye el cero. 
Flotante (real) | Número con decimales, positivo y negativo, también se incluye el cero.
 Complejo | Número con componente imaginario.
 Cadena de texto | Texto
 Boleanos | unicamente dos valores 'true o false'.
 Conjuntos | Colección de elementos no ordenados y no repetidos
 Listas |  Vector de elementos que pueden ser doferentes tipos de datos
 Tuplas | Lista inmutable de elementos
  Diccionarios |  Lista de eleentos que contienen claves y valores
 
 
Ahora realicemos ulgunas operaciones con diferentes tipos de información. Lo primero que  harémos será importar la <a href="https://es.m.wikipedia.org/wiki/Biblioteca_(inform%C3%A1tica)">biblioteca</a> que utilizarémos para el tratamiento de los datos: la biblioteca <a href="https://docs.python.org/es/3.10/library/math.html">math</a> que nos proporciona acceso a diferentes funciones matemáticas. Oprime el icono de play ▶️ en la siguiente celda de código:

In [ ]:
import math

Una vez importada, podremos utiizar esta biblioteca en nuestras rutinas llamandola por su nombre. Empecemos con algunas operaciones.
 
(i) $\small(2x4)+5$:

In [ ]:
2*4+5

(ii) $\small34^{3/2}$:

In [ ]:
34**3/2

(iii) $\small(254)^4$:

In [ ]:
254**4

Ahora, en la siguiente linea de código escribe la rutina para realizar esta operación: $\small(23)^5/4.5x10^5$. (Dentro de la  celda de código, el factor $\small x10^5$, se representa con la letra `e`)

In [ ]:
23**5/4.5e5

Para realizar operaciones utilizando funciones sobre cualquier tipo de número,  debemos emplear el código específico de la biblioteca `math`. Por ejemplo realicemos la siguiente operación:
$\small\sqrt{24}$

In [ ]:
math.sqrt(24)

En este <a href="https://docs.python.org/es/3.10/library/math.html">link</a> encontrarás  más ejemplos de funciones matemáticas de la biblioteca `math`. Si quisiéramos redondear el resultado a una cifra decimal podríamos utilizar la función `round()`.

In [ ]:
import math
round(math.sqrt(24),3)

También podemos definir una variable con nuestra operación para invocarla nuevamente y utilizarla todas las veces que la necesitemos

In [ ]:
raiz=math.sqrt(24)   # definimos nuestra variable con el nombre raiz
round(raiz, 3)          # definimos la  variable con el nombre raizround(raiz, 1)    # aplicamos la función round sobre nuestra variable (variable, cifras decimales de redondeo)

Ahora, probemos la siguiente operación:
$\small\sin(\pi/3$)

In [ ]:
x=math.sin(math.pi/3)
round(x, 3)

Google colabs trabaja con radianes asi que debemos utilizar la funcion `math.pi` para invocar $\small\pi$ en el código. Ahora es tu turno, escribe el código para obtener el resultado  de las siguientes operaciones redondeando el resultado a 3 cifras decimales: 
 
(i) $\small\log_{10}5$ 
 
(utiliza la función: `log10()`)

In [ ]:
y=math.log10(5)
round(y,3)

(ii)$\small\sqrt{cos(\pi/3)}$ 
 
(utiliza la función: `math.cos()`)

In [ ]:
z=math.sqrt(math.cos(math.pi/3))
round(z,3)

Para reducir el código, tambien podemos importar unicamente las operaciones que vamos a utilizar sin importar toda la biblioteca `math`, para el mismo ejemplo anterior, un código alternativo podría ser

In [ ]:
from math import sqrt, pi, cos
z1=sqrt(cos(pi/3))
round(z1,3)

0.707

Lo mas importante de utilizar las variables, es que una vez han sido definidas pueden volver a ser utilizadas para desarrollar más operaciones 🎉 .

Ahora realizarémos la siguiente operación:  $\small\sin(\pi/3)+cos(\pi/3)$. Podríamos escribir todo el código de esta operación; sin embargo, en las celdas de código previas ya definimos por separado la operaciones de este ejercicio:
 
$\small\ x=sin(\pi/3)$
 
$\small\ z=cos(\pi/3)$
 
En esta oportunidad no escribirémos esta parte de la operación ya que podremos invocar las dos variables.

In [ ]:
x+z

Ahora es tu turno, en la siguiente linea de código escribe la rutina para obtener el resultado de la siguiente operación: $\small\log_{10}5 +\small\sqrt{cos(\pi/3)}$
 
Recuerda que estas dos operaciones las dedarrollaste hace unos minutos asi que puedes utilizar las mismas variables.

 # ***Manejo de Listas (vectores y matrices)***
---
Cuando requieras utilizar (<a href="https://es.m.wikipedia.org/wiki/Vector_(inform%C3%A1tica)">listas</a>) para realizar el tratamiento de tus datos, podras utilizar la <a href="https://es.m.wikipedia.org/wiki/Biblioteca_(inform%C3%A1tica)">biblioteca</a> <a href="https://es.m.wikipedia.org/wiki/NumPy#:~:text=NumPy%20(pronunciado%20%2F%CB%88n%CA%8C,nivel%20para%20operar%20con%20ellas.">numpy</a> (numerical phyton), es la bilioteca principal de phyton para el desarrollo de cálculos con aplicaciones científicas, brindando herramientas para realizar cálculos con vectores y matrices. 
 
Supongamos que tenemos la siguiente serie de datos (1, 2, 3, 4 , 5 ) y queremos realizar diferentes operaciones con estos datos. 
 
Primero debemos importar la biblioteca que utilizaremos:(¡)`numpy`,  ésta biblioteca la invocaremos como `np`, se utilizan estas letras para reducir el texto en el código (pero  puedes utilizar las que desees, se utiliza`np` ya que todos lo hacen de esta forma). Enseguida creamos la lista con la función `np.array([])`

In [ ]:
import numpy as np
datos= np.array([1,2,3,4,5])
datos**2

array([ 1,  4,  9, 16, 25])

También podemos realizar operaciones con esta serie de datos, definir nuevas variables y operar estas nuevas variables.

In [ ]:
serie2=([3.1, 3.3,5,44,6])
serie3=serie2+datos
np.sqrt(serie3)

array([2.02484567, 2.30217289, 2.82842712, 6.92820323, 3.31662479])

Si deseamos generar una serie de números podemos utilizar la función `np.arange()` nuevamente

In [ ]:
serie=np.arange(1,50) 
serie

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Podemos cambiar el valor de cambio utilizando una tercera variable en la misma función

In [ ]:
serie2=np.arange(1,51,3)
serie2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

Ahora es tu turno 👊, con los conceptos aprendidos realiza la siguiente actividad: En la lista se muestran los volúmenes de titulación de diferentes muestras de HCl con una solución estandar de NaOH 0.250 M. 
 
<div align = "center"> Tabla 2. Volúmenes de titulación de muestras de HCl con una solución NaOH 0.250M.</div>
 
Ensayo| NaOH (mL)
-------------------|------------------
   1   | 22.503 
 2 | 17.906 
 3 | 19.403 
 3 | 22.403 
 3 | 11.403 
 3 | 14.403
 
Si el volúmen de las muestras HCl utilizados en cada titulación fue de 10.00 mL; crea una rutina que entregue como salida una matriz con los valores de concetración molar de cada muestra de HCL valorada.

---
#***Hoy aprendimos***
 
*  Introducción al entorno de google Colabs
*  Componentes de una rutina
*  Funciones de programación basicas en phyton
*  Definicion de variables, funciones y matrices en phyton
*  Operaciones básicas de funciones en phyton
 
---
#***Enlaces Recomendados***
 
*  Manual de NumPy: <a href="https://numpy.org/doc/stable/index.html">NumPy v1.21</a>
*  Tutorial de `numpy`: <a href="http://facundoq.github.io/courses/images/res/03_numpy.html">numpy</a>
*  Tutorial de `math`: <a href="https://docs.python.org/es/3/library/math.html">math</a>
*  Tutorial de matemáticas en phyton: (i) <a href="https://interactivechaos.com/es/manual/tutorial-de-python/variables">Matematicas en Phyton</a> (ii) <a href="https://personal.math.ubc.ca/~pwalls/math-python/jupyter/notebook/">Mathematical Phyton</a>
*  Tutorial de Álgebra lineal: <a href="https://relopezbriega.github.io/blog/2015/06/14/algebra-lineal-con-python/"> Álgebra Lineal con Phyton</a> 
 
---
#***Referencias***
 
*  A. Moreno. S. Córcoles. Aprende Phyton en un Fin de Semada. Time of software. 2018. ISBN 978-1719884838.

 