<a href="https://colab.research.google.com/github/wavallejol/ColabChem/blob/main/Sesi%C3%B3n6_Ley_de_Hess-Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sesión 6. Ley de Hess: Método de matrices**
***William Vallejo***
# **Objetivo**
 
1.   Determinar el cambio de entalpía de reacción aplicando la ley de Hess.
2.   Realizar cálculos termoquímicos utilizando matrices en el entorno Google Colabs.
---

 
# ***Introducción***
---
 
La  <a href="https://es.wikipedia.org/wiki/Ley_de_Hess"> ley de Hess</a> establece que si una reacción química ocurre a través de una serie de etapas, el valor del calor transferido para la reacción completa será igual a la suma del calor transferido en cada etapa individual, cumpliendose la relación:
 
$\small \Delta H_{r}^{o}= \sum \Delta H_{f}^{o}\kern 2pc (1)$
 
Dónde $\small \Delta H_{r}^{o}$ representa la entalplía de reacción bajo condiciones estándar y  $\small \Delta H_{f}^{o}$ representa la <a href="https://es.wikipedia.org/wiki/Entalp%C3%ADa_de_formaci%C3%B3n"> entalpía de formación estandar</a>  de las sustancias químicas que hacen parte de la reacción. Esta propiedad de las reacciones químicas es consecuencia directa de que la entalpía sea una función de estado. De forma general, para una reacción química se establece:
 
$\small aA+bB\rightarrow cC+dD\kern 2pc (2)$
 
La variación de la entalpía estándar de reacción a $\small 25^{o}C$ se expresa de la siguiente forma:
 
$\small \Delta {H_{r}^{o}}=c{H_{f}^{o}(C)}+d{H_{f}^{o}(D)}-a{H_{f}^{o}(A)}-b{H_{f}^{o}(B)}\kern 2pc (3)$
 
Dónde $\small \Delta H_{f}^{o}$ representa el valor de la entalpía estándar a 298 K. La ley de Hess permite determinar el valor de $\small \Delta H_{r}^{o}$ desconocido de diferentes tipos de reacción a partir de los valores de $\small \Delta H_{f}^{o}$ reportados en las tablas termodinámicas. 
 
Una reacción química puede ser representada matemáticamente de la siguiente manera:
 
$\small 0=\sum_{i=1}^{N} \nu_{i}B_{i}\kern 2pc(4)$
 
Dónde $\small \nu_{i}$ representa el coeficiente estequiométrico y $\small B_{i}$ representa la identidad del compuesto o elemento químico. El valor de $\small \nu_{i}$ será positivo para los productos de la reacción y $\small \nu_{i}$ será negativo para los reactivos. Una vez han sido balanceadas, las reacciones químicas pueden ser manipuladas como ecuaciones algebráicas. 
 
Los problemas de termoquímica convencionales que implican la determinación de valores de entalpía de reacción desconocidos, aplicando la ley de Hess, tienen como base de cálculo las propiedades de las ecuaciones algebráicas. De esta manera las ecuaciones químicas pueden ser sumadas, restadas entres sí, también pueden ser invertidas y multiplicadas para determinar el valor de $\small \Delta {H_{r}^{o}}$ para una etapa específica de un proceso que involucre varias reacciones químicas. 

La metodología de resolución muchas veces implica ensayo y error, sin embargo, dependiendo del número de reacciones químicas la complejidad puede incrementarse significativamente, haciendo tedioso el trabajo; no obstante, M. Khalil  <a href="https://pubs.acs.org/doi/10.1021/ed077p185">(Khalil, 2000)</a> reportó una metodología de resolución de este tipo de problemas utlizando matrices. 
 
Antes de continuar con la revisión del material, si tienes dudas respecto al  manejo de matrices y vectores, o el tipo de operaciones que puedes realizar con este tipo de variables, puedes revisar el material de <a href="https://github.com/wavallejol/ColabChem/blob/main/Sesi%C3%B3n1_Intro_A.ipynb"> la sesión 1</a> de este mismo repositorio. 
 
Ahora podemos dar inicio a la revisión del material para resolver problemas de termoquímica usando la ley de Hess y matrices

#***Actividad 1: Ley de Hess con matrices***
Tomando como referencia la ecuación (1), podemos escribir la ecuación 2 de la siguiente manera:
 
$\small 0=-aA-bBcC+dD \kern 2pc (5)$
 
Ahora podemos escribir la ecuación (5) como un vector de la siguiente manera:
 
$\begin{matrix}A\\ B\\ C\\ D\\ 
\end{matrix}$ $
\begin{bmatrix}
-a\\ 
-b\\ 
+c\\ 
+d\\ 
\end{bmatrix}$ $\small \qquad(6)$
 
Se tendrá una columna por cada reacción química que se tenga en el proceso y una fila por cada sustancia química. A continuación, se presenta un ejemplo para ilustarlo de una mejor manera. Expresemos como matrices las ecuaciones químicas (7 y 8):
 
$\small S_{(s)}+O_{2(g)}\rightarrow SO_{2(g)}\kern 3pc\Delta H_{r}^{o}=-297\enspace kJmol^{-1}\kern 2pc (7)$
 
$\small 2SO_{2(g)}+O_{2(g)}\rightarrow 2SO_{3(g)} \kern 2pc \Delta H_{r}^{o}=-198\enspace kJmol^{-1}\kern 2pc (8)$
 
Primero creamos una lista que representará todas las sustancias químicas que aparecen en las dos reacciones (7 y 8):
 
$\begin{matrix}\small S_{(s)}\\ \small O_{2(g)}\\ \small SO_{2(g)}\\ \small SO_{3(g)}\\ 
\end{matrix}$ 
 
Ahora, creamos la matríz de las dos reacciones químicas:
 
$\small \kern 3pc ec.\enspace(7) \kern 3pc ec.\enspace(8)$
 
$\begin{matrix}\small S_{(s)}\\ \small O_{2(g)}\\ \small SO_{2(g)}\\ \small SO_{3(g)}\\ 
\end{matrix}$ 
$\begin{bmatrix}
-1&&&0\\ 
-1&&&-1\\ 
+1&&&-2\\ 
0&&&+2\\ 
\end{bmatrix}$ $\small \qquad (9)$
 
Cada columna dentro de la matríz representa una reacción química, y cada número representa un coeficiente estequiométrico de la reacción. La primera columna de la matríz (costado izquierdo), representa los coeficientes estequiométricos de la reacción (8) y la segunda columna de la matríz (costado derecho) representa los coeficientes estequiométricos de la reacción (9).
 
Ahora, a partir de las ecuaciones 7 y 8, debemos  determinar el valor de $\small \Delta H^{o}$ para la reacción de combustión de $\small S_{2(g)}$ en presencia de $\small O_{2(g)}$ de acuerdo a la siguiente reacción química: 
 
$\small 2S_{(s)}+3O_{2(g)}\rightarrow 2SO_{3(g)}\kern 2pc (10)$
 
Para resolver esta pregunta, aplicaremos el álgebra lineal a sistemas de ecuaciones lineales utilizando matrices. Primero, transcribirémos nuestro sistema de ecuaciones químicas a la forma $\small Ax=b$ M: <a href="https://pubs.acs.org/doi/10.1021/ed077p185">(Fuente: Khalil, 2000)</a> :
 
$\begin{bmatrix}
\small \nu_{11} & \small \nu_{12} & \cdots&\small \nu_{1R}\\ 
\small \nu_{21}&\small \nu_{22}&\cdots&\small \nu_{2R}\\  
\vdots&\vdots&\vdots&\vdots\\ 
\small \nu_{N1}&\small \nu_{N2}&\cdots&\small \nu_{NR}\\  
\end{bmatrix}$
$\begin{bmatrix}
\small s_{1}\\ 
\small s_{2}\\  
\vdots\\ 
\small s_{R}\\  
\end{bmatrix}$=
$\begin{bmatrix}
\small \nu_{net1}\\ 
\small \nu_{net2}\\  
\vdots\\ 
\small \nu_{netN}\\  
\end{bmatrix}$
$\small \kern 2pc  (11)$
 
$\small \kern 5pc A \kern 5pc x \kern 4pc b$
 
Dónde, A representa la matríz con los coeficientes estequiométricos de las reacciones conocidas (7 y 8). En nuestro ejemplo, la matríz mostrada en la ecuación (9) sería $\small A$. El vector $\small (x)$ representa el vector que debe ser determinado, este vector nos indicará el valor por el que deberémos multiplicar cada una de las reacciones químicas conocidas (ec. 7 y 8). El vector $\small (x)$ tendrá tantos elementos cómo valores de entalpia de reaccion conocido tengamos, en nuestro ejemplo tenemos 2 reacciones con valores de entalpía conocidos, por lo tanto, éste vector tendrá dos elementos. Finalmente, $\small (b)$ representa el vector resultado (vector con los coeficientes estequiométricos de la reacción para la cúal nos interesa determinar el valor de $\small \Delta_{r} H^{o}$).

Primero, representamos nuestro sistema de reacciones  de la forma $\small Ax=b$:
 
$\begin{bmatrix}
-1&&&0\\ 
-1&&&-1\\ 
+1&&&-2\\ 
0&&&+2\\ 
\end{bmatrix}$
$\begin{bmatrix}
\small s_{1}\\ 
\small s_{2}\\  
\end{bmatrix}$=
$\begin{bmatrix}
\small -2\\ 
\small -3\\  
\small 0\\ 
\small +2\\  
\end{bmatrix}$
$\small \kern 2pc  (12)$
 
$\small \qquad A \kern 6pc x \kern 2pc b$
 
Para resolver este sistema de ecuaciones existen diferentes métodos: (i) método de sustitución , (ii) método de igualación, (iii) método de reducción, (iv) método gráfico, (v) método de Gauss y (vi) el método de Cramer. Sin embargo, Phyton tiene algunas funciones que nos permiten resolver este sistema de ecuaciones utilizando la función `np.linalg.lstsq()`.
 
Tomando como referencia la ecuación $\small Ax=b$ que acabamos de generar, en la siguiente celda de código procedemos a crear la matríz de coeficientes A.

In [ ]:
import numpy as np        #importamos la biblioteca para operar matrices
A=np.array([[-1,0], 
            [-1,-1], 
            [1,-2], 
            [0,2]])       #creamos la matriz de coeficientes A
A

array([[-1,  0],
       [-1, -1],
       [ 1, -2],
       [ 0,  2]])

Ahora procedemos a crear el vector resultado $\small (b)$.

In [ ]:
b=np.array([-2,-3,0,2])    

array([-2, -3,  0,  2])

Procedemos a resolver el sistema de ecuaciones con  la función `np.linalg.lstsq()`.

In [ ]:
x=np.linalg.lstsq(A,b, rcond=1) 
x[0]

array([2., 1.])

El resultado de la resolución nos muestra que el vector x es:

$\begin{bmatrix}
\small s_{1}\\ 
\small s_{2}\\  
\end{bmatrix}$=
$\begin{bmatrix}
\small 2\\ 
\small 1\\  
\end{bmatrix}$ $\kern 5pc (13)$

Apartir de este vector y el valor $\small \Delta H_{r}^{o}$ de las reacciones 7 y 8 podemos obtener el valor de $\small \Delta H_{r}^{o}$ de la reacción (11):

$\small \Delta H_{r(11)}^{o}=\begin{bmatrix}
\small s_{1}\\ 
\small s_{2}\\  
\end{bmatrix}$
$\begin{bmatrix}
\small -297&
\small -198
\end{bmatrix}$ $\kern 2pc (14)$

En la siguiente celda de código, procedemos a realizar el cálculo de la entalpía de la reacción:

In [ ]:
H=np.array([-297,-198])
ENTALPÍA=print("H_reacción", round(x[0]@H, 1), "kJ/mol")

H_reacción -792.0 kJ/mol


#***Actividad 2: Ejemplo cálculo de la Entalpía de una reacción***

Utilizando el método de resolución por matrices, en la siguiente línea de código escribe la rutina para determinar el valor del cambio de entalpía de la siguiente reacción química:

 
$\small NH_{3(g)}+2O_{2(g)}\rightarrow HNO_{3(l)}+H_{2}O_{(l)} \kern 3pc (15)$

A partir de las siguientes reacciones:

$\small 4NH_{3(g)}+5O_{2(g)}\rightarrow 4NO_{(g)}+6H_{2}O_{(l)} \kern 2pc \Delta H_{r}^{o}=-1170\enspace kJmol^{-1}\kern 1pc  (16)$

$\small 2NO_{(g)}+O_{2(g)}\rightarrow 2NO_{2(g)} \kern 6pc \Delta H_{r}^{o}=-114\enspace kJmol^{-1}\kern 1pc  (17)$


$\small 3NO_{2(g)}+H_{2}O_{(l)}\rightarrow 2HNO_{3(l)}+NO_{(g)} \kern 2pc \Delta H_{r}^{o}=-72\enspace kJmol^{-1}\kern 1pc  (18)$

Procedemos a seguir los pasos establecidos:

 1.   Representamos nuestro sistema de reacciones  de la forma $\small Ax=b$ y luego Utilizamos la rutina creada para resolver el sistema de ecuaciones:

$\small \kern 5pc ec.(16) \kern 1pc ec.(17)  \kern 1pc ec.(18)$

$\begin{matrix}\small NH_{3(g)}\\ \small O_{2(g)}\\ \small NO_{(g)}\\ \small H_{2}O_{(g)}\\ \small NO_{2(g)}\\ \small HNO_{3(l)}\\ 
\end{matrix}$ 
$\begin{bmatrix}
-4&&&0&&&0\\ 
-5&&&-1&&&0\\ 
+4&&&-2&&&+1\\ 
+6&&&0&&&-1\\ 
0&&&+2&&&-3\\ 
0&&&0&&&+2\\ 
\end{bmatrix}$
$\begin{bmatrix}
\small s_{1}\\ 
\small s_{2}\\  
\small s_{3}\\  
\end{bmatrix}$=
$\begin{bmatrix}
\small -1\\ 
\small -2\\  
\small 0\\ 
\small +1\\ 
\small 0\\  
\small +1\\ 
\end{bmatrix}$
$\small \kern 2pc (19)$

$\small \kern 8pc A \kern 8pc x \kern 3pc b$ 

In [ ]:
A=np.array([[-4,0,0], 
            [-5,-1,0], 
            [4,-2,1], 
            [6,0,-1],
            [0,2,-3],
            [0,0,2]])                    #creamos matriz de coeficientes (A)
b=np.array([-1,-2,0,1,0,1])              #creamos vector resultado (b)
x=np.linalg.lstsq(A,b, rcond=1)          #resolvemos sistema de ecuaciones
H=np.array([-1170,-114,-72])             #creamos el vector con los valores de entalpía
print("H=", round(x[0]@H, 1), "kJ/mol")  #calculamos el valor de la entalpía

H= -414.0 kJ/mol


#***Actividad 3: Ejercicios cálculo de la Entalpía de una reacción***

**Ejercicio 1.**

Ahora es tu turno. Utilizando el método de resolución por matrices, en la siguiente línea de código, escribe la rutina para determinar el valor del cambio de entalpía de la siguiente reacción química:

 
$\small C_{2}H_{2(g)}+2H_{2(g)}\rightarrow C_{2}H_{6(g)}\kern 6pc (20)$

A partir de las siguientes reacciones:

$\small 2C_{2}H_{2(g)}+5O_{2}{(g)}\rightarrow 4CO_{2(g)}+2H_{2}O_{(l)}  \kern 2pc \Delta H_{r}^{o}=-2600\enspace kJmol^{-1}\kern 1pc  (21)$

$\small 2C_{2}H_{6(g)}+7O_{2}{(g)}\rightarrow 4CO_{2(g)}+6H_{2}O_{(l)} \kern 2pc \Delta H_{r}^{o}=-3210\enspace kJmol^{-1}\kern 1pc  (22)$

$\small H_{2(g)}+\frac{1}{2}O_{2(g)}\rightarrow H_{2}O_{(l)} \kern 6pc \Delta H_{r}^{o}=-286\enspace kJmol^{-1}\kern 1pc  (23)$


**Ejercicio 2.**

Utilizando el método de resolución por matrices, en la siguiente línea de código, escribe la rutina para determinar el valor del cambio de entalpía de la siguiente reacción química:

 
$\small 2CO_{2(g)}+H_{2}O_{(g)}\rightarrow C_{2}H_{2(g)}+\frac{5}{2}O_{2(g)} \kern 6pc (24)$

A partir de las siguientes reacciones:

$\small C_{2}H_{2(g)}+2H_{2}{(g)}\rightarrow C_{2}H_{6(g)} \kern 5pc \Delta H_{f}^{o}=-94.5\enspace kJmol^{-1}\kern 1pc  (25)$

$\small H_{2}O_{(g)}\rightarrow H_{2(g)}+\frac{1}{2}O_{2(g)}  \kern 6pc \Delta H_{f}^{o}=71.2\enspace kJmol^{-1}\kern 2pc  (26)$

$\small C_{2}H_{6(g)}+\frac{7}{2}O_{2(g)}\rightarrow 2CO_{2(g)}+3H_{2}O_{(g)} \kern 2pc \Delta H_{f}^{o}=-283\enspace kJmol^{-1}\kern 1pc  (27)$

---
#***Enlaces Recomendados***
 
*  Manual de NumPy: <a href="https://numpy.org/doc/stable/index.html">NumPy v1.21</a>
*  Tutorial de `numpy`: <a href="http://facundoq.github.io/courses/images/res/03_numpy.html">numpy</a>
*  Tutorial de Álgebra lineal: <a href="https://relopezbriega.github.io/blog/2015/06/14/algebra-lineal-con-python/"> Álgebra Lineal con Phyton</a> 


#***Referencias***
 
*  M. I. Khalil. Calculating Enthalpy of Reaction by Matrix Method. $\small J. Chem. Ed. 2000, 77, 2, 185.$ <a href="https://pubs.acs.org/doi/10.1021/ed077p185">doi.org/10.1021/ed077p185</a>
 
---