<a href="https://colab.research.google.com/github/wavallejol/ColabChem/blob/main/Session1_English.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Session 1: Introduction to Google Colaboratory**

# **Objectives**
 
1.   To know the Google Colaboratory environment.
2.   To learn basic programming commands.

#**Introduction**
---
 
<div align="justify"> This document is an introductory guide to applying basic programming concepts with <a href="https://en.wikipedia.org/wiki/Python_(programming_language)">phyton</a> to solve chemistry exercises ⚗🧪. The Phyton software is a programming language used in a wide variety of applications, with the advantage of applicability to different work platforms; besides, phyton is open access software, being accessible to anyone who wishes to use it 😆. You can find a book on scientific programming aimed at chemistry at the following link <a href="https://github.com/weisscharlesj/SciCompforChemists/tree/master/Book_PDF">Scientific Computing for Chemists</a>.  You did not need prior programming knowledge for using this guide. The different links will connect it with internet pages to review the unknown concepts or those you should remember 📖..
 
 <a href="https://research.google.com/colaboratory/">Google Colaboratory</a> (also known as Google Colabs) is a virtual machine in the cloud that allows you to run phyton programming without configuring anything on your computer (download or install new programs); all you need is internet access and a Gmail account, you can even work directly on your cell phone 📱.  Colabs notebooks are Jupyter notebooks hosted in Colab, for more information about the Jupyter project you can see this link: <a href="https://jupyter.org/">Jupyter</a>. Colab gives you easiness to share content simply and effectively through Google Drive 🗂. You can see this link <a href="https://www.youtube.com/watch?v=inN8seMm7UI">introductory video</a> about google Colabs (duration 3:09 minutes). One of the advantages of using programming codes for the treatment of experimental or theoretical data is that you can create  <a href="https://en.wikipedia.org/wiki/Subroutine#Python_example">routines</a> of code (small codes) to solve unknown quantities, extract and visualize information. These routines can be used as many times as you want and can be adapted according to your needs. Typically, a routine is composed of 3 elements ✔: 
 
(i) The input: It can be a number, a function, an array.
 
(ii) The process: It represents what we will do with our input (e.g., a mathematical, logical, or comparative operation).
 
(iii) The output: After process execution on the input, we produced the result (e.g., a plotting, string).

In a traditional protocol, we should create a file with the routine (e.g., inputs, process, and output) then, we should save the file, and finally, we should use the phyton software to run the routine. At Google Colabs we save the first two steps for using cloud computing. We only have to write the routine and execute it, without any additional step. In Google Colabs we have two types of cells through which we can work:
 
(¡) The text cell 🔤: It allows you to add text, links, and figures to provide information (what are you reading is written in a text cell).
 
(ii) The code cell: In this cell, the input, the program, and the output of our routine are written. The cell you find below is an example of a code cell.</div>

In [ ]:
# here we are going to write our code

In the code cell, the text you put after the symbol `#` is not part of the routine you will execute. This text indicates additional information about the code. At this point, we can take our first steps to learn a little about this powerful tool.

#**First programs**
---
We will create our first program: we will use the command`print()`, this command outputs a string (e.g., quotes within the parentheses). In the next code cell, we will place our first program.
 
Click on the next code cell and then, click on the "play" icon ▶️  placed at the left side of the code cell.

In [ ]:
 print("hello, world!") # quote inside the parentheses will appear as outputing

After the code was executed; the message written within the command `print()` was generated as "output".  Now, in the next cell, write the code to generate your name as the output.

You have written your first routine, a first step for learning this powerful tool. Now we will try the command`input()`, this command allows us to read information entered by a user from the keyboard.  To see an example, press the play icon ▶️  ∫in the next code cell.  The routine will greet you and ask for your name. Type it and then, hit the "enter" key.

In [ ]:
print("Hello, I will be your guide in this first session. Please type your name:")
Nombre=input()
print(Nombre,", it is marvelous you are interested in learning phyton.")

The previous routine allowed you to read the information entered by the user (in this case you) in response to a question previously established through the code.

Python recognizes different types of information we can generate and use during our experiments. Table 1 shows a summary of the type of information we can handle with python.
 
<div align = "center"> Table 1. Description of different types of information we can utilize in phyton.(Source: A.Moreno, S. Corcoles, 2018.</a>)</div>
 
Type of information| Description
-------------------|------------------
 Integer | Number without decimals, positive and negative, zero is also included. 
Float | Number with decimals, positive and negative, zero is also included. 
 Complex | Number with an imaginary component.
 String | Text.
 Bolean | Only two values ​​'true or false'.
 Sets | Selection of unordered and non-repeating elements.
 Lists |  Array of elements that can be different types of data.
 Tuples | Immutable list of items
  Dictionaries |  List of elements that contain keys and values
 
 
Now, We can do some operations with different types of information. First import the <a href="https://en.wikipedia.org/wiki/Python_(programming_language)#Libraries">library</a> we will use to process the data. The library <a href="https://docs.python.org/3/library/math.html?highlight=math">math</a> which provides us with access to different mathematical functions. Press the play icon ▶️  in the following code cell:

In [ ]:
import math

Once we imported it, we can use this library in our routines by calling it by its name. Then let's get started with some operations.
 
(i) $\small(2x4)+5$:

In [ ]:
2*4+5

(ii) $\small34^{3/2}$:

In [ ]:
34**3/2

(iii) $\small(254)^4$:

In [ ]:
254**4

ANow, in the following line of code, we write the routine to perform this operation: $\small(23)^5/4.5x10^5$. (
Inside the code cell, the factor $\small x10^5$, is representing with the letter `e`)

In [ ]:
23**5/4.5e5

To perform operations using functions on any type of number, we must use the specific code of the library
 `math`. Let's carry out the following operation: $\small\sqrt{24}$

In [ ]:
math.sqrt(24)

In this link <a href="https://docs.python.org/3/library/math.html?highlight=math">math</a> you will find more examples of the `math` library. To round the result to one decimal place, we could use the `round()` function. 
The first parameter of the `round()` function corresponds to the rounding variable and, the second parameter indicates the number of decimal places.

In [ ]:
round(math.sqrt(24),3)

We can also define a variable with our operation to invoke it again and use it as many times as we need.

In [ ]:
root=math.sqrt(24)   # root will be the name of the variable 
round(root, 3)       # we round to three decimal places our variable

Now, let's try the following operation:
$\small\sin(\pi/3$)

In [ ]:
x=math.sin(math.pi/3)
round(x, 3)

Google colabs uses radians and, we use the function `math.pi` to invoke $\small\pi$ in the code. Nnow it's your turn. Write the code to obtain the result of the following operations rounding the result to 3 decimal places:
 
(i) $\small\log_{10}5$ 
 
(use function: `log10()`)

In [ ]:
y=math.log10(5)
round(y,3)

(ii)$\small\sqrt{cos(\pi/3)}$ 
 
(use the function: `math.cos()`)

In [ ]:
z=math.sqrt(math.cos(math.pi/3))
round(z,3)

To reduce the code, we can import all properties from the library `math` for using `import *` in the code. with this command you can utilize all operation of `math` library 🎉. For the same operation in ht previous code cell. 

In [ ]:
from math import *
z1=sqrt(cos(pi/3))
round(z1,3)

The most important about using variables is once you have defined them, you can use them again to develop more operations 🎉 .

Now, we will perform the following operation: $\small\sin(\pi/3)+cos(\pi/3)$. We could write all the code for this operation; However, in the previous code cells, we already defined these operations separately:
 
$\small\ x=sin(\pi/3)$
 
$\small\ z=cos(\pi/3)$
 
This time, we will not write this part of the operation since we can invoke both variables.

In [ ]:
x+z

Now it is your turn. In the following code cell, write the routine to obtain the result of the next operation: $\small\log_{10}5 +\small\sqrt{cos(\pi/3)}$
 
Remember, you carried out these two operations in previous code cells. You can use (invoke) these variables.

 # ***List operation (array and matrix)***
---

  <div align="justify">When you uses (<a href="https://en.wikipedia.org/wiki/List_(abstract_data_type)">lists</a>) for manipulating your data, you can use the library <a href="https://en.wikipedia.org/wiki/NumPy">numpy</a> (numerical phyton). This is Phyton's main library for carrying out calculations with scientific applications, providing tools to perform calculations with array and matrix.
 
Suppose we have the following data series (1, 2, 3, 4 , 5 ) and we want to perform different operations with this data.
 

First, we must import the library `numpy`, We will invoke this library as `np`. We used these letters to reduce the caracters in the code (but you can use whatever you want), we use `np` since it is the conversion utilized by the phyton community. Next, we create the a list with the function `np.array([])` using our data.</div>

In [ ]:
import numpy as np
datos= np.array([1,2,3,4,5])
datos**2

array([ 1,  4,  9, 16, 25])

We can perform operations with this data series, define new variables and operate these new variables also.

In [ ]:
serie2=([3.1, 3.3,5,44,6])
serie3=serie2+datos
np.sqrt(serie3)

array([2.02484567, 2.30217289, 2.82842712, 6.92820323, 3.31662479])

To generate a series of numbers, we can use the function `np.arange()`. In the next code cell, we will generate data of 50 numbers start in 1 and finish in 50. The last number is not included in the series.

In [ ]:
serie=np.arange(1,50) 
serie

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

We can change the step value using a third parameter of the same function

In [ ]:
serie2=np.arange(1,51,3)
serie2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

Now is your turn 👊, With the concepts learned, perform the following activity: Table 2 shows the titration volumes of different samples of HCl with a standard solution of 0.250 M NaOH.
 
<div align = "center"> Table 2. Volumes of 0.250M NaOH utilized in the titration of samples of HCl of unknown concentration. </div>
 
Sample| NaOH (mL)
-------------------|------------------
   1   | 22.503 
 2 | 17.906 
 3 | 19.403 
 4 | 22.403 
 5 | 11.403 
 6 | 14.403
 
If the volume of the HCl samples used in each titration was 10.00 mL. To create a routine to obtain the molar concentration values ​​for each titrated HCl sample.


---
#***Today we learned***
 
*  Introduction to the google Colabs environment
*  Components of a routine
*  Basic programming functions in phyton
*  Definition of variables, functions and array in phyton
 
---
#***Recommended Links***
 
*  NumPy Manual : <a href="https://numpy.org/doc/stable/index.html">NumPy v1.21</a>
* `numpy` Tutorial : <a href="https://cs231n.github.io/python-numpy-tutorial/">numpy</a>
*  `math` Tutorial: <a href="https://realpython.com/python-math-module/">math</a>
*  Mathematics in phyton tutorial : (i) <a href="https://github.com/drvinceknight/Python-Mathematics-Handbook">Mathematics in phyton</a> (ii) <a href="https://personal.math.ubc.ca/~pwalls/math-python/jupyter/notebook/">Mathematical Phyton</a>

 
---
#***References***
 
*  A. Moreno. S. Córcoles. Aprende Phyton en un Fin de Semada. Time of software. 2018. ISBN 978-1719884838.

*  C. Weiss. Scientific Computing for Chemist. 2020. CC-BY-NC-SA 4.0. <a href="https://github.com/weisscharlesj/SciCompforChemists/tree/master/Book_PDF"> Scientific Computing for Chemist</a>

 